server:
  port: 8081
spring:
  datasource:
    password: Sepehr@12345
    username: sepehr
    url: jdbc:mysql://localhost:3306/microservice_project
   
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: REGISTERATION   
    
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
      
  instance:
    instance-id: REGISTERATION